config/routes.rb
Rails.application.routes.draw do
  resources :pils
  root 'pils#index'

  get 'report', to: 'pils#report'
  get 'report_src', to: 'pils#report_src'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pil.rb
class Pil < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pils_controller.rb
class PilsController < ApplicationController
  before_action :set_pil, only: [:show, :edit, :update, :destroy]


  def report
    @pils = Pil.all
  end

  def report_src

  end

  # GET /pils
  # GET /pils.json
  def index
    @pils = Pil.all
  end

  # GET /pils/1
  # GET /pils/1.json
  def show
  end

  # GET /pils/new
  def new
    @pil = Pil.new
  end

  # GET /pils/1/edit
  def edit
  end

  # POST /pils
  # POST /pils.json
  def create
    @pil = Pil.new(pil_params.merge(:drafttoken => SecureRandom.hex(10)))


    respond_to do |format|
      if @pil.save
        format.html {redirect_to edit_pil_path(@pil,:step => "2")
          # redirect_to @pil, notice: 'Pil was successfully created.'
          }
        format.json {render :show, status: :created, location: @pil}
      else
        format.html {render :new}
        format.json {render json: @pil.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /pils/1
  # PATCH/PUT /pils/1.json
  def update
    params[:step] ||= "1"
    respond_to do |format|
      if @pil.update(pil_params)
        format.html {
          # redirect_to @pil, notice: 'Pil was successfully updated.'
          if params[:step] == "1"
            redirect_to edit_pil_path(@pil,:step => "2")
          elsif params[:step] == "2"
            redirect_to edit_pil_path(@pil,:step => "3")
          else
            redirect_to @pil, notice: 'Заявка успешно заполнена'
          end
                    }
        # format.json {render :show, status: :ok, location: @pil}
      else
        format.html {render :edit}
        format.json {render json: @pil.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /pils/1
  # DELETE /pils/1.json
  def destroy
    puts("destroy")
    @pil.destroy
    respond_to do |format|
      format.html {redirect_to pils_url, notice: 'Заявка успешно удалена'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pil
    @pil = Pil.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pil_params
    params.require(:pil).permit(:lastname, :firstname, :middlename, :email, :passportSeries, :passportNumber, :passportIssuedDate, :passportIssuedCode, :passportIssuedBy, :birthDate, :passportBirthPlace, :passportRegion, :workinn, :drafttoken,:utm_source,:utm_medium,:utm_campaign,:product,:limit,:deliveryType,:deliveryDate,:deliveryAdress,:dopDoc1,:dopDoc2,:isAccepted,:isDeal,:dealDate)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pils_helper.rb
module PilsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anketa</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/suggestions-jquery@18.11.1/dist/css/suggestions.min.css" type="text/css" rel="stylesheet"/>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <!--[if lt IE 10]>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajaxtransport-xdomainrequest/1.0.1/jquery.xdomainrequest.min.js"></script>
  <![endif]-->
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/suggestions-jquery@18.11.1/dist/js/jquery.suggestions.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">


</head>

<body>

<!-- <Заголовок> -->
<%= render "shared/header" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2">

      <!-- <Левое меню> -->
<%= render "shared/leftMenu" %>
    </div>
    <!--      <div class="col-sm-9 col-md-10">-->
    <!--        <div class="container-fluid">-->
<%#= yield %>
    <!--        </div>-->
    <!--      </div>-->
    <!--    </div>-->
    <!--  </div>-->


    <div class="col-12 col-sm-9 col-md-9">
      <div class="container-fluid ">
        <%= yield %>
        <h1>

        </h1>

      </div>
    </div>
  </div>
</div>
</body>
<!--bg-success-->
</html>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
        m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

    ym(52589482, "init", {
        id:52589482,
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true,
        trackHash:true
    });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/52589482" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-135352010-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-135352010-1');
</script>

app/views/pils/_form.html.erb
<div>

  <% params[:step] ||= '1' %>

  <h6>
    <% params %>
  </h6>
</div>


<%= form_with(model: pil, local: true) do |form| %>
  <% if pil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pil.errors.count, "error") %> prohibited this pil from being saved:</h2>

      <ul>
        <% pil.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <% if params[:step] == "1" %>
    <%= form.hidden_field :utm_source, value: params[:utm_source] %>
    <%= form.hidden_field :utm_medium, value: params[:utm_medium] %>
    <%= form.hidden_field :utm_campaign, value: params[:utm_campaign] %>

    <div class="form-group row ">
      <%= form.label "Фамилия", class: "col-sm-2 col-form-label " %>
      <div class="col-sm-10">
        <%= form.text_field :lastname, class: "form-control", placeholder: "Иванов" %>
        <small class="form-text text-muted col-form-label">
          Это тестовая форма, не указывайте реальные данные. Поле содержит автоподстановку
        </small>
      </div>
    </div>

    <div class="form-group row ">
      <%= form.label "Имя", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :firstname, class: "form-control", placeholder: "Иван" %>
        <small class="form-text text-muted col-form-label">
          Это тестовая форма, не указывайте реальные данные. Поле содержит автоподстановку
        </small>
      </div>
    </div>

    <div class="form-group row ">
      <%= form.label "Отчество", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :middlename, class: "form-control", placeholder: "Иванович" %>

        <small class="form-text text-muted col-form-label">
          Это тестовая форма, не указывайте реальные данные. Поле содержит автоподстановку
        </small>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :email, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.email_field :email, class: "form-control ", placeholder: "ivanov.ivan@mail.com" %>

        <small class="form-text text-muted col-form-label">
          Это тестовая форма, не указывайте реальные данные. Поле с типом = email и Клавиатура телефона должна
          адаптироватся.
        </small>
      </div>
    </div>
  <% end %>

  <% if params[:step] == "2" %>
    <div class="form-group row ">
      <%= form.label "Серия Паспорта", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :passportSeries, class: "form-control", placeholder: "9999" %>
        <small class="form-text text-muted col-form-label">
          Это тестовая форма, не указывайте реальные данные.
        </small>
      </div>
    </div>

    <div class="form-group row ">
      <%= form.label "Номер паспорта", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :passportNumber, class: "form-control", placeholder: "123456" %>
        <small class="form-text text-muted col-form-label">
          Это тестовая форма, не указывайте реальные данные.
        </small>
      </div>
    </div>

    <div class="form-group row ">
      <%= form.label "Дата выдачи паспорта", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.date_field :passportIssuedDate, class: "form-control", placeholder: "ГГГГ-ММ-ДД" %>
        <small class="form-text text-muted col-form-label">
          Не указывайте реальные данные. Календарь должен быть нативным
        </small>
      </div>

    </div>

    <div class="form-group row ">
      <%= form.label "Код подразделения", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :passportIssuedCode, class: "form-control", placeholder: "999-001" %>
        <small class="form-text text-muted col-form-label">
          Не указывайте реальные данные.
        </small>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label "Кем выдан паспорт", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :passportIssuedBy, class: "form-control", placeholder: "ОВД По Городу Москва" %>
        <small class="form-text text-muted col-form-label">
          Не указывайте реальные данные.
        </small>
      </div>
    </div>

    <div class="form-group row ">
      <%= form.label "Дата рождения", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.date_field :birthDate, class: "form-control", placeholder: "ГГГГ-ММ-ДД" %>
        <small class="form-text text-muted col-form-label">
          Не указывайте реальные данные.Календарь должен быть нативным
        </small>
      </div>
    </div>

    <div class="form-group row ">
      <%= form.label "Место рождения", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :passportBirthPlace, class: "form-control", placeholder: "гор. Москва" %>
        <small class="form-text text-muted col-form-label">
          Не указывайте реальные данные.
        </small>

      </div>
    </div>

    <div class="form-group row ">
      <%= form.label "Регион прописки", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :passportRegion, class: "form-control", placeholder: "Московская Область" %>
        <small class="form-text text-muted col-form-label">
          Не указывайте реальные данные.
        </small>
      </div>
    </div>

    <div class="form-group row ">
      <%= form.label "Наименование / ИНН работодателя", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :workinn, class: "form-control", placeholder: "Введите название, адрес, ИНН или ОГРН" %>
        <small class="form-text text-muted col-form-label">
          Не указывайте реальные данные. Поле содержит автоподстановку
        </small>

      </div>
    </div>

<!--    <div class="form-group row ">-->
      <%#= form.label :drafttoken, class: "col-sm-2 col-form-label" %>
<!--      <div class="col-sm-10">-->
        <%#= form.text_field :drafttoken, class: "form-control" %>
<!--      </div>-->
<!--    </div>-->
  <% end %>

  <% if params[:step] == "3" %>
    <div class="form-group row ">
      <%= form.label "Продукт", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10 form-group">
        <%= form.select :product, ['', 'Карта с Кэшбеком', 'Карта с Грейсом', 'Кредит наличными', 'Ипотека'], {}, {class: "form-control"} %>
        <small class="form-text text-muted col-form-label">
          Можно выбрать любой продукт
        </small>
      </div>
    </div>
    <div class="form-group row ">
      <%= form.label "Желаемый лимит", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.number_field :limit, class: "form-control", placeholder: "50 000" %>
        <small class="form-text text-muted col-form-label">
          Поле для указания желаемого лимита.
        </small>
      </div>
    </div>
  <% end %>
  <% if params[:step] == "delivery" %>
    <div class="form-group row ">
      <%= form.label "Желаемый способ получения продукта", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.select :deliveryType, ['', 'Доставка Курьером банка', 'Доставка Почтой', 'Через отделение'], {}, {class: "form-control"} %>
      </div>
    </div>

    <div class="form-group row ">
      <%= form.label "Дата доставки курьером", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.date_field :deliveryDate, class: "form-control", placeholder: "ГГГГ-ММ-ДД" %>
        <small class="form-text text-muted col-form-label">
          Поле имеет смысл только для доставки
        </small>
      </div>
    </div>
    <div class="form-group row ">
      <%= form.label "Адрес доставки", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :deliveryAdress, class: "form-control", placeholder: "Укажите адрес доставки" %>
        <small class="form-text text-muted col-form-label">
          Поле имеет смысл только для доставки
        </small>
      </div>
    </div>
  <% end %>

  <% if params[:step] == "postback" %>
  <div class="form-group row ">
    <%= form.label "Флаг одобрения", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.check_box :isAccepted, class: ""%>
    </div>
  </div>

  <div class="form-group row ">
    <%= form.label "Флаг выдачи", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.check_box :isDeal, class: ""%>
    </div>

  </div>

  <div class="form-group row ">
    <%= form.label "Дата выдачи", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.date_field :dealDate, class: "form-control", placeholder: "ГГГГ-ММ-ДД" %>

    </div>
  </div>

    <% end %>




  <div>
    <%= hidden_field_tag 'step', params[:step] %>
  </div>

  <% if params[:step] != "postback" %>
  <div class="progress">
    <% if params[:step] == '1'
         chanse = '40'
       elsif params[:step] == '2'
         chanse = '60'
       elsif params[:step] == '3'
         chanse = '85'

       elsif params[:step] == 'delivery'
         chanse = '95'
       else
         chanse = '99'
       end
    %>

    <div class="progress-bar progress-bar-striped" role="progressbar" style="width: <%=chanse.to_i %>%" aria-valuenow=<%= chanse %> aria-valuemin="0" aria-valuemax="100">


      <%= 'Ваши шансы на продукт' %> <%= chanse %> <%= "%" %>
    </div>
  </div>
  <% end %>
  <div>
    <% if params[:step] == '1'
         sub_text = 'Далее'
       elsif params[:step] == '2'
         sub_text = 'Далее'
       elsif params[:step] == '3'
         sub_text = 'Отправить заявку'
       elsif params[:step] == 'delivery'
         sub_text = 'Готово'
         else
         sub_text = 'Готово'
       end


    %>
    <%= form.submit sub_text, :class => "btn btn-primary btn-block" %>
  </div>
<% end %>
<br>

<script type="text/javascript">
    $("#pil_lastname").suggestions({
        token: "530b45ff577449be7b0612c14e78a826fd768f21",
        type: "NAME",
        params: {parts: ["surname"]},
        count: 3,
        /* Вызывается, когда пользователь выбирает одну из подсказок */
        onSelect: function (suggestion) {
            console.log(suggestion);
        }
    });

    $("#pil_firstname").suggestions({
        token: "530b45ff577449be7b0612c14e78a826fd768f21",
        type: "NAME",
        params: {parts: ["name"]},
        count: 3,
        /* Вызывается, когда пользователь выбирает одну из подсказок */
        onSelect: function (suggestion) {
            console.log(suggestion);
        }
    });

    $("#pil_middlename").suggestions({
        token: "530b45ff577449be7b0612c14e78a826fd768f21",
        type: "NAME",
        params: {parts: ["patronymic"]},
        count: 3,
        /* Вызывается, когда пользователь выбирает одну из подсказок */
        onSelect: function (suggestion) {
            // console.log(suggestion);
        }
    });
    $("#pil_email").suggestions({
        token: "530b45ff577449be7b0612c14e78a826fd768f21",
        type: "EMAIL",
        count: 3,
        // params: {parts: ["domain"]},
        suggest_local: false,

        /* Вызывается, когда пользователь выбирает одну из подсказок */
        onSelect: function (suggestion) {
            // console.log(suggestion);
        }
    });

    $("#pil_workinn").suggestions({
        token: "530b45ff577449be7b0612c14e78a826fd768f21",
        type: "PARTY",
        count: 3,


        /* Вызывается, когда пользователь выбирает одну из подсказок */
        onSelect: function (suggestion) {
            console.log(suggestion);
        }
    });
</script>

app/views/pils/edit.html.erb
<% if params[:step] == "delivery" %>
  <h2>Укажите способ доставки</h2>
<%else %>
<h2>Заявка на продукт</h2>
  <% end %>

<%= render 'form', pil: @pil %>

<!--<%#= link_to 'Просмотр', @pil , {:class => "btn btn btn-secondary"}%> |-->
<h3></h3>
<%= link_to 'Вернутся на главную', pils_path , {:class => "btn btn-info"}%>

app/views/pils/index.html.erb
<p id="notice"><%= notice %></p>


  <h2>Заявки на продукт</h2>


<div class="table-responsive">
  <table class = "table">
    <tr class="border">
      <th>ФИО</th>
      <th></th>
      <th></th>
      <th></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @pils.each do |pil| %>
      <tr class="border">
        <td><%= pil.lastname %> <%= pil.firstname%> <%=  pil.middlename%></td>
        <td><%= link_to ' ', pil_path(pil,:step => "1"), :class => " glyphicon glyphicon-eye-open"%></td>
        <td><%= link_to ' ', edit_pil_path(pil,:step => "delivery"), :class => "glyphicon glyphicon-calendar" %></td>
        <td><%= link_to ' ', pil, method: :delete, data: { confirm: 'Действительно удалить заявку?' }, :class => "glyphicon glyphicon-remove" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'Новая заявка органика', new_pil_path(:step => "1"), :class => "btn btn-primary btn-block"%>
<br>
<%= link_to 'Новая заявка google контекст', new_pil_path(:utm_source => "google",:utm_medium => "cpc"), :class => "btn btn btn-primary btn-block"%>
<br>
<%= link_to 'Новая заявка yandex поиск', new_pil_path(:utm_source => "yandex",:utm_medium => "search"), :class => "btn btn btn-primary btn-block"%>

app/views/pils/new.html.erb
<h1>Новая заявка</h1>

<%= render 'form', pil: @pil %>

<%= link_to 'Вернутся на главную', pils_path , {:class => "btn btn-info"}%>

app/views/pils/report.html.erb
<h3>Всего заявок : <%=@pils.count %> </h3>

<h4>     (органика: <%=Pil.where(utm_source: [nil, ""]).count %>)</h4>
<h4>     (Контекст: <%=Pil.where(utm_medium: "cpc").count %>)</h4>
<h4>     (Поиск: <%=Pil.where(utm_medium: "search").count %>)</h4>




<h3>Одобрено заявок : <%=@pils.where(isAccepted: 1).count %></h3>

<h4>     (органика: <%=Pil.where(utm_source: [nil, ""],isAccepted: 1).count %>)</h4>
<h4>     (Контекст: <%=Pil.where(utm_medium: "cpc",isAccepted: 1).count %>)</h4>
<h4>     (Поиск: <%=Pil.where(utm_medium: "search",isAccepted: 1).count %>)</h4>


<h3>Выдано : <%=@pils.where(isDeal: 1).count %></h3>

<h4>     (органика: <%=Pil.where(utm_source: [nil, ""],isDeal: 1).count %>)</h4>
<h4>     (Контекст: <%=Pil.where(utm_medium: "cpc",isDeal: 1).count %>)</h4>
<h4>     (Поиск: <%=Pil.where(utm_medium: "search",isDeal: 1).count %>)</h4>

app/views/pils/report_src.html.erb
<h1>Вся база заявок в сыром виде</h1>

<div class ='container-fluid'>
<h4><%=Pil.all.to_json%></h4>
</div>

app/views/pils/show.html.erb
<p id="notice"><%= notice %></p>


<strong>ФИО:</strong>
  <%= @pil.lastname %>  <%= @pil.lastname %>
  <%= @pil.middlename %>
<br>

<strong>Паспорт:</strong>
<%= @pil.passportSeries %> <%= @pil.passportNumber %>
<br>

<strong>Продукт:</strong>
<%= @pil.product %>

<br>

<strong>Лимит:</strong>
<%= @pil.limit %>
</p>

<%= link_to 'Редактировать', edit_pil_path(@pil) , :class => " btn btn-info"%> |
<%#= link_to 'Вернутся на главную', pils_path , {:class => "btn btn-info"}%>

<%= link_to 'Выбрать доставку', edit_pil_path(@pil,:step => "delivery"), :class => "btn btn-primary" %>


<br>

<br>
<%= link_to 'Для обратной интеграции: Указать результаты по заявке', edit_pil_path(@pil,:step => "postback"), :class => "btn btn-warning " %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%=root_path %>>Тестовая заявка</a>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li class="<%= 'active' if current_page? (pils_path)or current_page? (root_path)  %>">

          <a href=<%= pils_path%>>Список заявок</a>
        </li>
        <li>
          <a href=<%= report_path %>>Отчетность</a></li>
        </li>
        <li>
          <a href=<%= report_src_path%>>Доступ к базе заявок</a>
        </li>

      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_leftMenu.html.erb
<!--<ul class="nav nav-pills nav-stacked">-->
<!--  <li role="presentation" class="<%#= 'active' if current_page? (pils_path)or current_page? (root_path)  %>"><a href=<%#=pils_path %>>Список заявок</a></li>-->

<!--  <li role="presentation" class=""><a href=<%#=pils_path %>>Отчетность</a></li>-->
<!--  <li role="presentation" class=""><a href=<%#=pils_path %>>Список заявок</a></li>-->
<!--  <li role="presentation" class=""><a href=<%#=pils_path %>>Список заявок</a></li>-->

<!--</ul>-->